name: Code Quality

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Cache a directory
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('uv.lock') }}

      - name: Install the project
        run: |
          uv sync --all-extras --all-groups
          uv pip install ruff

  ruff:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Cache a directory
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('uv.lock') }}

      - name: Run Ruff
        run: uv run ruff check --output-format=github .

  pyright:
    runs-on: ubuntu-latest

    steps:
      - uses: jakebailey/pyright-action@v1
        with:
          version: 1.1.399
